[package]
name = "zinc_blink"
version = "0.0.1"

[features]
default = ["mcu_stm32f4"]
mcu_stm32f4 = ["zinc/mcu_stm32f4"]

[dependencies]
zinc = { path =  "../zinc" }
macro_zinc = { path = "../zinc/macro_zinc" }
rust-libcore = "*"
